cabal-version: 2.4
name:          atto-bench
version:       0.1.0.0
build-type:    Simple

executable atto-bench
  main-is:             Main.hs
  build-depends:
      base       >= 4.14 && < 5
    , bytestring >= 0.11
    , attoparsec >= 0.14
    , deepseq    >= 1.4
    , clock      >= 0.8
    , filepath   >= 1.4
  default-language:    Haskell2010
  ghc-options:         -O2 -Wall -threaded
