name = "grip-json-props"
version = "0.1.0"
defaultTargets = ["GripProps"]

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "GripProps"
globs = ["GripProps", "GripProps.+"]

[[require]]
name = "grip"
git = "https://github.com/jonaprieto/lean-grip.git"
rev = "v0.3.4"

[[require]]
name = "grip-json"
path = ".."

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"
